name: Core C CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]

    name: "💦 ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment (macOS)
      if: runner.os == 'macos'
      run: |
        brew update
        brew install autoconf automake pybind11 virtualenv

    - name: Setup environment (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y --no-install-recommends build-essential pybind11-dev virtualenv python3-dev

    #- name: Setup libfec
    #  run: git clone https://github.com/jgaeddert/libfec.git && cd libfec && ./configure && make && sudo make install

    - name: bootstrap
      run: ./bootstrap.sh

    - name: configure
      run: ./configure

    - name: make
      run: make -j 2

    - name: make check-doc
      run: |
        python3 -m venv /tmp/liquid
        source /tmp/liquid/bin/activate
        pip install pybind11 numpy matplotlib
        make check-doc

    - name: make check
      run: make -j 2 check

    - name: make install
      run: sudo make install

    - name: ldconfig (Linux)
      if: runner.os == 'Linux'
      run: sudo ldconfig

    - name: make check-link
      run: make check-link
